### ISSUE TITLE
Official Implementation

### ISSUE THREAD

**Issue by greeneggsandyaml** [hrshtv/pytorch-lmu#1]
Hello,

Thank you for your great work on this implementation. I'm trying to find the official source, because I had a few questions. You linked the following url:
https://github.com/NarsimhaChilkuri/Parallelizing-Legendre-Memory-Unit-Training

Unfortunately, there's nothing there at the moment. Did this repo exist at some point? If it did and you cloned it, would you be able to send it to me (by email or whatever)?

**Comment by hrshtv** [comment]
It seems that it has been merged with the [official Keras repository](https://github.com/nengo/keras-lmu) ([`line 628, keras_lmu/layers.py`](https://github.com/nengo/keras-lmu/blob/c871bb561c54f38e477fc4895f198ac157187c45/keras_lmu/layers.py#L628))
